2021-04-03 14:06:55,883 (1346213/MainThread) litecli.main ERROR - sql: 'h', error: OperationalError('Not connected to database.')
2021-04-03 14:06:55,884 (1346213/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 114, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-04-03 14:07:05,426 (1346213/MainThread) litecli.main ERROR - sql: '.dat', error: OperationalError('Not connected to database.')
2021-04-03 14:07:05,427 (1346213/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 114, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-04-03 14:07:07,253 (1346213/MainThread) litecli.main ERROR - sql: '.databases', error: OperationalError('Not connected to database.')
2021-04-03 14:07:07,254 (1346213/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 114, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-04-03 14:07:40,613 (1350710/MainThread) litecli.main ERROR - sql: 'show tables', error: OperationalError('near "show": syntax error')
2021-04-03 14:07:40,614 (1350710/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 121, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 125, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "show": syntax error\n'
2021-04-03 14:08:01,459 (1350710/MainThread) litecli.main ERROR - sql: 'show .tables', error: OperationalError('near "show": syntax error')
2021-04-03 14:08:01,459 (1350710/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 121, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 125, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "show": syntax error\n'
2021-04-03 14:08:22,036 (1350710/MainThread) litecli.main ERROR - sql: 'SHOW TABLES', error: OperationalError('near "SHOW": syntax error')
2021-04-03 14:08:22,037 (1350710/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 121, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 125, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "SHOW": syntax error\n'
2021-04-03 14:08:24,811 (1350710/MainThread) litecli.main ERROR - sql: 'ls', error: OperationalError('near "ls": syntax error')
2021-04-03 14:08:24,812 (1350710/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 121, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 125, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "ls": syntax error\n'
2021-04-03 14:08:28,549 (1350710/MainThread) litecli.main ERROR - sql: 'table', error: OperationalError('near "table": syntax error')
2021-04-03 14:08:28,549 (1350710/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 121, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 125, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "table": syntax error\n'
2021-04-03 14:08:59,798 (1360934/MainThread) litecli.main ERROR - sql: '.databases', error: OperationalError('Not connected to database.')
2021-04-03 14:08:59,799 (1360934/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.9/site-packages/litecli/sqlexecute.py", line 114, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
